### ISSUE TITLE
view_item formatting.

### ISSUE THREAD

**Issue by pixelmachine** [nystudio107/craft-instantanalytics-ga4#27]
### Question
The documentation has an example of manually creating and sending a view_item event. However the example doesn't show how to add the nested items that are needed. Looking at the code and GA4 MP docs this is what I've come up with:

```php

{% set viewItem = instantAnalytics.create.ItemParameter %}
{% do  viewItem.
        .setItemId(product.sku)
        .setItemName(product.title)
        .setCurrency(cart.getPaymentCurrency())
        .setPrice(product.price)
        .setItemCategory(product.type)
        .setQuantity(1)
%}

{% set viewItemEvent = instantAnalytics.create.ViewItemEvent %}
{% do  viewItemEvent
        .setValue(product.price)
        .setCurrency(cart.getPaymentCurrency())
        .addItem(viewItem)
%}

{% do  instantAnalytics.viewItemEvent(viewItemEvent) %}
```

Does this look correct?

Additionally, what's the best way to debug? I can `dump()` the objects created but I wondered if there was a better way to see what's happening.

Finally there's a small typo in the docs. After the [Event Reference](https://nystudio107.com/docs/instant-analytics-ga4/using.html#event-reference) table you have `{% do instantAnalytics.viewItemEvent(searchEvent) %}` but you should be passing in `viewItemEvent` not `searchEvent`.

**Comment by khalwat** [comment]
Yep, looks right to me. The way you're debugging things is likely fine; you can also use XDebug on the PHP side of things to make it easier.

And then open up your Google Analytics backend and see what is sent there.

I fixed the typo in the docs, thanks.

**Comment by pixelmachine** [comment]
Thanks @khalwat  

It seems Google doesn't show commerce data submissions on new sites until a certain amount has been submitted. So in this case and another previous case it wasn't possible for me to see what data was sent until the site was live and the data was flowing.

**Comment by khalwat** [comment]
Makes sense -- I wish I knew of a better way. Perhaps they have some kind of sandbox mode that works more immediately for testing?

**Comment by pixelmachine** [comment]
Not sure, if I find anything I'll let you know!

**Comment by pixelmachine** [comment]
@khalwat re. the typo I mentioned. I just realised it's still wrong:
```twig
{% do instantAnalytics.viewItemEvent(viewItemEvent) %}
```
Should be 
```twig
{% do instantAnalytics.addEvent(viewItemEvent) %}
```
Right?

**Comment by khalwat** [comment]
haha -- fail. Yep, you're right. Fixed it for real this time.
